import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Instructions: Save your icon image as 'source-icon.jpg' or 'source-icon.png' in the root directory
const sourceIconPath = path.join(__dirname, 'source-icon.jpg');
const sourceIconPathAlt = path.join(__dirname, 'source-icon.png');

async function convertIcon() {
  try {
    // Create build directory if it doesn't exist
    const buildDir = path.join(__dirname, 'build');
    if (!fs.existsSync(buildDir)) {
      fs.mkdirSync(buildDir, { recursive: true });
    }

    // Check which source file exists
    let sourceFile;
    if (fs.existsSync(sourceIconPath)) {
      sourceFile = sourceIconPath;
    } else if (fs.existsSync(sourceIconPathAlt)) {
      sourceFile = sourceIconPathAlt;
    } else {
      console.error('❌ Error: Please save your icon as "source-icon.jpg" or "source-icon.png" in the root directory');
      process.exit(1);
    }

    console.log(`📁 Using source icon: ${path.basename(sourceFile)}\n`);

    // Generate PNG icons in different sizes
    const sizes = [16, 24, 32, 48, 64, 128, 256, 512];
    
    for (const size of sizes) {
      await sharp(sourceFile)
        .resize(size, size, {
          fit: 'contain',
          background: { r: 0, g: 0, b: 0, alpha: 0 }
        })
        .png()
        .toFile(path.join(buildDir, `icon_${size}x${size}.png`));
      console.log(`✓ Created icon_${size}x${size}.png`);
    }

    // Create main icon.png (256x256)
    await sharp(sourceFile)
      .resize(256, 256, {
        fit: 'contain',
        background: { r: 0, g: 0, b: 0, alpha: 0 }
      })
      .png()
      .toFile(path.join(buildDir, 'icon.png'));
    console.log('✓ Created icon.png');

    // For Windows .ico, we'll just use the PNG and let electron-builder handle it
    console.log('ℹ️  Windows .ico will be generated by electron-builder from icon.png');

    console.log('\n✅ All icons generated successfully!');
    console.log('You can now run: npm run electron:build:win');
  } catch (error) {
    console.error('❌ Error converting icon:', error);
    process.exit(1);
  }
}

convertIcon();
